name: Master CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache SBT ivy cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}
      - name: Cache .jabba
        uses: actions/cache@v2
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jabba-${{ hashFiles('build.sbt') }}
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Compile and test
        run: |
          csbt \
            'set core / Compile / scalacOptions += "-Werror"' \
            'set macros / Compile / scalacOptions += "-Werror"' \
            compile \
            test \
            < /dev/null
